// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.646
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func SignupForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form class=\"space-y-4 md:space-y-6\" action=\"/v1/api/signup\" method=\"POST\" id=\"signup-form\"><div><label for=\"email\" class=\"label label-text\">Your email</label> <input type=\"email\" name=\"email\" placeholder=\"name@company.com\" required class=\"input input-bordered w-full\"></div><div><label for=\"password\" class=\"label label-text\">Password</label> <input type=\"password\" name=\"password\" placeholder=\"••••••••\" required class=\"input input-bordered w-full\"></div><div><label for=\"confirm-password\" class=\"label label-text\">Confirm password</label> <input type=\"password\" name=\"confirm-password\" placeholder=\"••••••••\" required class=\"input input-bordered w-full\"></div><button type=\"submit\" class=\"w-full btn btn-primary\">Create an account</button><p class=\"text-sm font-light text-gray-300\">Already have an account? <button onclick=\"switchForms()\" type=\"button\" class=\"font-medium hover:underline text-secondary\">Login here</button></p></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
