// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.646
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func SignupForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form class=\"space-y-4 md:space-y-6\" action=\"/v1/api/signup\" method=\"POST\" id=\"signup-form\"><div><label for=\"email\" class=\"block mb-2 text-sm font-medium text-white\">Your email</label> <input type=\"email\" name=\"email\" class=\"border sm:text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500\" placeholder=\"name@company.com\" required></div><div><label for=\"password\" class=\"block mb-2 text-sm font-medium text-white\">Password</label> <input type=\"password\" name=\"password\" placeholder=\"••••••••\" class=\"border sm:text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500\" required></div><div><label for=\"confirm-password\" class=\"block mb-2 text-sm font-medium text-white\">Confirm password</label> <input type=\"password\" name=\"confirm-password\" placeholder=\"••••••••\" class=\"border sm:text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500\" required></div><button type=\"submit\" class=\"w-full text-white focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center bg-blue-600 hover:bg-blue-700 focus:ring-blue-800\">Create an account</button><p class=\"text-sm font-light text-gray-400\">Already have an account? <button onclick=\"switchForms()\" type=\"button\" class=\"font-medium text-blue-600 hover:underline dark:text-blue-500\">Login here</button></p></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
